services:
  backend:
    build:
      context: .
    ports:
      - "6000:6000"
    env_file:
      - .env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    restart: on-failure
    command: npm start
